# Generated by Django 4.2 on 2023-04-15 10:09

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserWorks',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_first_name', models.CharField(max_length=255)),
                ('user_last_name', models.CharField(max_length=255)),
                ('user_id', models.IntegerField()),
                ('user_main_skills', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None)),
                ('user_image_url', models.CharField(default='', max_length=255)),
                ('main_skills', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None)),
                ('likes_count', models.IntegerField(default=0)),
                ('image_url', models.CharField(default='', max_length=255)),
                ('start_text', models.CharField(default='', max_length=255)),
                ('name', models.CharField(default='New work <django.db.models.fields.IntegerField> from <django.db.models.fields.CharField>', max_length=255)),
                ('comments', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=[], size=None)),
                ('open_comments', models.BooleanField(default=False)),
                ('blocks', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], size=None)),
                ('date', models.DateField(default=datetime.datetime(2023, 4, 15, 15, 9, 43, 537238))),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=[], size=None)),
                ('file_urls', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=[], size=None)),
            ],
        ),
        migrations.CreateModel(
            name='WorkBlockType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.IntegerField()),
                ('image_urls', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=[], size=None)),
                ('text', models.CharField(max_length=255)),
                ('order', models.IntegerField()),
            ],
        ),
    ]
