# Generated by Django 4.2 on 2023-04-15 12:07

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userworks',
            name='likes_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], size=None),
        ),
        migrations.AlterField(
            model_name='userworks',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 4, 15, 17, 7, 52, 607451)),
        ),
    ]
