# Generated by Django 4.2 on 2023-04-15 12:36

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_userworks_likes_list_alter_userworks_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserComments',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('text', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='userworks',
            name='comments',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], size=None),
        ),
        migrations.AlterField(
            model_name='userworks',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 4, 15, 17, 36, 7, 752018)),
        ),
    ]
