# Generated by Django 4.1.7 on 2023-05-15 11:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecondarySkillsType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("background_color", models.CharField(max_length=255)),
                ("font_color", models.CharField(max_length=255)),
                ("checked", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="UserSubscribtions",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "subs_list",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(), default=[], size=None
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("email", models.EmailField(max_length=255, unique=True)),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("image_url", models.CharField(blank=True, default="", max_length=255)),
                (
                    "available_main_skills",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(), default=[], size=None
                    ),
                ),
                (
                    "selected_main_skills",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(), default=[], size=None
                    ),
                ),
                (
                    "available_secondary_skills",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(), default=[], size=None
                    ),
                ),
                (
                    "selected_secondary_skills",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(), default=[], size=None
                    ),
                ),
                ("city", models.CharField(blank=True, default="", max_length=255)),
                ("company", models.CharField(blank=True, default="", max_length=255)),
                ("subscribers_count", models.IntegerField(blank=True, default=0)),
                ("works_count", models.IntegerField(blank=True, default=0)),
                ("phone", models.IntegerField(blank=True, default=0)),
                (
                    "additional_links",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(default="", max_length=255),
                        default=[],
                        size=None,
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
