# Generated by Django 4.1.7 on 2023-05-15 11:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecondarySkillsType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("background_color", models.CharField(max_length=255)),
                ("font_color", models.CharField(max_length=255)),
                ("checked", models.BooleanField(default=False)),
            ],
        ),
    ]
