# Generated by Django 4.2 on 2023-04-13 11:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubscribtions',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('subs_list', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], size=None)),
            ],
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='additional_links',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=255), default=[], size=None),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='available_main_skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=255), default=[], size=None),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='available_secondary_skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=255), default=[], size=None),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='city',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='company',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='image_url',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='phone',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='selected_main_skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=255), default=[], size=None),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='selected_secondary_skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=255), default=[], size=None),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='subscribers_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='works_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
