# Generated by Django 4.1.7 on 2023-03-12 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_useraccount_gender_useraccount_is_premium'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='useraccount',
            old_name='surname',
            new_name='last_name',
        ),
    ]
