name: Run linting

on:
  pull_request:
    branches: [master]
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  linting:
    runs-on: ubuntu-latest
    env:
       working-directory: ./frontend
    defaults:
      run:
        working-directory: ${{ env.working-directory }}
    steps:
      - name: log
        run: pwd | ll
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install nodejs
        uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'
      - name: Install dependencies
        run: npm ci
      - name: Lint code
        run: npm run lint
